<?php
declare(strict_types=1);
if(!hasRole('social-service-officer')&&!hasRole('subject-officer')){http_response_code(403);exit('You do not have permission to access this page.');}
require_once __DIR__.'/../../config/database.php';require_once __DIR__.'/../../includes/activity.php';require_once __DIR__.'/../../includes/eligibility.php';
$subject=hasRole('subject-officer');$activePage=$subject?'aid-distribution':'aid-requests';$errors=[];$success=(string)($_SESSION['flash_success']??'');unset($_SESSION['flash_success']);$db=database();$userId=(int)$_SESSION['user_id'];
if($_SERVER['REQUEST_METHOD']==='POST'){
 $beneficiaryId=filter_input(INPUT_POST,'beneficiary_id',FILTER_VALIDATE_INT);$itemId=filter_input(INPUT_POST,'item_id',FILTER_VALIDATE_INT);$quantity=filter_input(INPUT_POST,'quantity',FILTER_VALIDATE_INT);$disability=trim((string)($_POST['disability_notes']??''));$notes=trim((string)($_POST['notes']??''));$powerInput=trim((string)($_POST['prescribed_power']??''));$signed=isset($_POST['medical_officer'],$_POST['grama_niladhari'],$_POST['social_services'],$_POST['divisional_secretary']);
 if(!verifyCsrfToken((string)($_POST['csrf_token']??'')))$errors[]='Your session expired.';if(!$beneficiaryId||!$itemId||!$quantity||$quantity<1)$errors[]='Select a beneficiary, item, and valid quantity.';if(mb_strlen($disability)<2||mb_strlen($disability)>500)$errors[]='Enter valid disability details.';if(mb_strlen($notes)>1000)$errors[]='Notes cannot exceed 1000 characters.';if(!$signed)$errors[]='All four official sign-offs are required.';
 if(!$errors){try{
  $scope=$db->prepare("SELECT b.id FROM beneficiaries b JOIN districts d ON d.id=b.district_id JOIN ds_divisions ds ON ds.id=b.ds_division_id JOIN gn_divisions gn ON gn.id=b.gn_division_id WHERE b.id=:id AND b.ds_division_id=(SELECT ds_division_id FROM users WHERE id=:user) AND b.status='active' AND b.full_name<>'' AND b.nic<>'' AND b.address<>'' AND b.disability<>''");$scope->execute(['id'=>$beneficiaryId,'user'=>$userId]);if(!$scope->fetchColumn())throw new RuntimeException('Beneficiary must be active, in your division, and have complete name, NIC, address, district, and disability details.');
  $eligibility=beneficiaryEligibility($db,$beneficiaryId,$itemId);if(!$eligibility['item']||$eligibility['item']['distribution_type']!=='request-based')throw new RuntimeException('This item does not require an aid request.');if(!$eligibility['eligible'])throw new RuntimeException($eligibility['reason']);
  $itemText=strtolower($eligibility['item']['item_name'].' '.$eligibility['item']['category_name'].' '.$eligibility['item']['variety']);$isLens=str_contains($itemText,'contact')&&str_contains($itemText,'lens');$power=null;if($isLens){if($powerInput===''||!is_numeric($powerInput))throw new RuntimeException('A valid prescribed power is required for a contact lens request.');$power=round((float)$powerInput,2);if($power < -30||$power > 30)throw new RuntimeException('Prescribed power must be between -30.00 and +30.00.');}
  $pending=$db->prepare("SELECT COUNT(*) FROM aid_requests ar JOIN inventory_items i ON i.id=ar.item_id WHERE ar.beneficiary_id=:beneficiary AND i.category_id=:category AND ar.status IN ('pending','approved')");$pending->execute(['beneficiary'=>$beneficiaryId,'category'=>$eligibility['item']['category_id']]);if((int)$pending->fetchColumn())throw new RuntimeException('An active request already exists for this beneficiary and aid category.');
  $stmt=$db->prepare('INSERT INTO aid_requests(beneficiary_id,item_id,quantity,disability_notes,prescribed_power,notes,medical_officer_approved,grama_niladhari_approved,social_services_approved,divisional_secretary_approved,submitted_by) VALUES(:beneficiary,:item,:quantity,:disability,:power,:notes,1,1,1,1,:user)');$stmt->execute(['beneficiary'=>$beneficiaryId,'item'=>$itemId,'quantity'=>$quantity,'disability'=>$disability,'power'=>$power,'notes'=>$notes?:null,'user'=>$userId]);$id=(int)$db->lastInsertId();logActivity('Aid Requests','Submitted fully signed aid distribution request','AR-'.str_pad((string)$id,4,'0',STR_PAD_LEFT),'pending');$_SESSION['flash_success']='Fully signed aid request submitted for Admin approval.';unset($_SESSION['csrf_token']);header('Location: dashboard.php?page='.($subject?'aid-distribution':'aid-requests'));exit;
 }catch(Throwable $e){error_log($e->getMessage());$errors[]=$e instanceof RuntimeException?$e->getMessage():'Unable to submit aid request.';}}
}
try{$s=$db->prepare("SELECT b.id,b.full_name,b.nic,b.address,b.disability,d.name district_name,ds.name division_name FROM beneficiaries b JOIN districts d ON d.id=b.district_id JOIN ds_divisions ds ON ds.id=b.ds_division_id WHERE b.status='active' AND b.ds_division_id=(SELECT ds_division_id FROM users WHERE id=:user) ORDER BY b.full_name");$s->execute(['user'=>$userId]);$beneficiaries=$s->fetchAll();$items=$db->query("SELECT i.id,i.item_name,i.variety,c.name category_name,(LOWER(CONCAT(i.item_name,' ',i.variety,' ',c.name)) LIKE '%contact%lens%') is_lens FROM inventory_items i JOIN item_categories c ON c.id=i.category_id WHERE c.status='active' AND c.distribution_type='request-based' ORDER BY i.item_name,i.variety")->fetchAll();$s=$db->prepare('SELECT ar.*,b.full_name,b.nic,i.item_name,i.variety FROM aid_requests ar JOIN beneficiaries b ON b.id=ar.beneficiary_id JOIN inventory_items i ON i.id=ar.item_id WHERE ar.submitted_by=:user ORDER BY ar.id DESC');$s->execute(['user'=>$userId]);$requests=$s->fetchAll();}catch(PDOException $e){error_log($e->getMessage());$beneficiaries=$items=$requests=[];$errors[]='Aid request workflow is unavailable.';}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aid Requests | WIDMS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="assets/css/admin-dashboard.css" rel="stylesheet"></head><body><?php require $subject?__DIR__.'/../../includes/subject-officer-sidebar.php':__DIR__.'/../../includes/social-service-officer-sidebar.php';?><div class="admin-shell"><header class="topbar"><div class="d-flex align-items-center gap-3"><button class="menu-button" id="menu-button">&#9776;</button><h1>Aid Distribution Requests</h1></div></header><main class="dashboard-content aid-requests-page"><?php if($success):?><div class="alert alert-success"><?=htmlspecialchars($success,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($errors):?><div class="alert alert-danger"><?=htmlspecialchars(implode(' ',$errors),ENT_QUOTES,'UTF-8')?></div><?php endif;?>
<section class="aid-form-card"><div class="aid-card-header"><h2>Submit New Aid Distribution Request</h2><small>Complete beneficiary details and all four sign-offs are mandatory</small></div><form method="post" class="aid-request-form"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken(),ENT_QUOTES,'UTF-8')?>"><fieldset><legend>Beneficiary and Aid</legend><div class="aid-form-grid two-columns"><label>Registered Beneficiary *<select name="beneficiary_id" id="beneficiary_id" required><option value="">Select beneficiary</option><?php foreach($beneficiaries as $b):?><option value="<?=(int)$b['id']?>" data-name="<?=htmlspecialchars($b['full_name'],ENT_QUOTES,'UTF-8')?>" data-nic="<?=htmlspecialchars($b['nic'],ENT_QUOTES,'UTF-8')?>" data-address="<?=htmlspecialchars($b['address'],ENT_QUOTES,'UTF-8')?>" data-district="<?=htmlspecialchars($b['district_name'],ENT_QUOTES,'UTF-8')?>" data-division="<?=htmlspecialchars($b['division_name'],ENT_QUOTES,'UTF-8')?>" data-disability="<?=htmlspecialchars($b['disability'],ENT_QUOTES,'UTF-8')?>"><?=htmlspecialchars($b['full_name'].' — '.$b['nic'].' — '.$b['division_name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label>Aid Requested *<select name="item_id" id="item_id" required><option value="">Select request-based item</option><?php foreach($items as $i):?><option value="<?=(int)$i['id']?>" data-lens="<?=(int)$i['is_lens']?>"><?=htmlspecialchars($i['item_name'].($i['variety']?' — '.$i['variety']:''),ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label></div><div id="beneficiary-details" class="alert alert-light border" hidden></div><div class="aid-form-grid two-columns"><label>Nature of Disability *<input name="disability_notes" id="disability_notes" required maxlength="500"></label><label>Quantity *<input type="number" name="quantity" value="1" min="1" required></label></div><label id="power-field" hidden>Prescribed Contact Lens Power *<input type="number" name="prescribed_power" id="prescribed_power" min="-30" max="30" step="0.01" placeholder="e.g. -2.00 or +1.50"></label><label class="full-field">Additional Notes<textarea name="notes" rows="2" maxlength="1000"></textarea></label></fieldset><fieldset><legend>Official Sign-offs (all required)</legend><div class="official-grid"><label><input type="checkbox" name="medical_officer" required> Government Medical Officer</label><label><input type="checkbox" name="grama_niladhari" required> Grama Niladhari</label><label><input type="checkbox" name="social_services" required> Social Service Officer</label><label><input type="checkbox" name="divisional_secretary" required> Divisional Secretary</label></div></fieldset><div class="aid-form-actions"><button class="submit-aid-button">Submit Fully Signed Request</button><small>Admin makes the next approval decision</small></div></form></section>
<section class="submitted-requests-card"><div class="submitted-header"><h2>My Submitted Requests</h2></div><div class="submitted-table-wrap"><table class="submitted-table"><thead><tr><th>ID</th><th>Beneficiary</th><th>NIC</th><th>Aid</th><th>Power</th><th>Qty</th><th>Approvals</th><th>Date</th><th>Status</th></tr></thead><tbody><?php if(!$requests):?><tr><td colspan="9" class="aid-requests-empty">No requests submitted yet.</td></tr><?php else:foreach($requests as $r):?><tr><td>AR-<?=str_pad((string)$r['id'],4,'0',STR_PAD_LEFT)?></td><td><?=htmlspecialchars($r['full_name'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['nic'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['item_name'].($r['variety']?' — '.$r['variety']:''),ENT_QUOTES,'UTF-8')?></td><td><?=$r['prescribed_power']!==null?sprintf('%+.2f',(float)$r['prescribed_power']):'—'?></td><td><?=(int)$r['quantity']?></td><td><?=array_sum([(int)$r['medical_officer_approved'],(int)$r['grama_niladhari_approved'],(int)$r['social_services_approved'],(int)$r['divisional_secretary_approved']])?> / 4</td><td><?=date('d M Y',strtotime($r['created_at']))?></td><td><?=ucfirst($r['status'])?></td></tr><?php endforeach;endif;?></tbody></table></div></section></main></div><script src="assets/js/admin-dashboard.js"></script><script>
const bs=document.getElementById('beneficiary_id'),is=document.getElementById('item_id'),bd=document.getElementById('beneficiary-details'),dn=document.getElementById('disability_notes'),pf=document.getElementById('power-field'),p=document.getElementById('prescribed_power');bs?.addEventListener('change',()=>{const o=bs.selectedOptions[0];if(!o?.value){bd.hidden=true;return}bd.innerHTML=`<strong>${o.dataset.name}</strong><br>NIC: ${o.dataset.nic}<br>Address: ${o.dataset.address}<br>District: ${o.dataset.district} / ${o.dataset.division}<br>Disability: ${o.dataset.disability}`;bd.hidden=false;dn.value=o.dataset.disability||''});is?.addEventListener('change',()=>{const required=is.selectedOptions[0]?.dataset.lens==='1';pf.hidden=!required;p.required=required;if(!required)p.value=''})
</script></body></html>
