USE widms;

CREATE TABLE IF NOT EXISTS beneficiary_registration_requests (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    district_id INT UNSIGNED NOT NULL,
    ds_division_id INT UNSIGNED NOT NULL,
    gn_division_id INT UNSIGNED NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    nic VARCHAR(20) NOT NULL,
    date_of_birth DATE NOT NULL,
    gender ENUM('male','female','other') NOT NULL,
    phone VARCHAR(25) NULL,
    address VARCHAR(255) NOT NULL,
    disability VARCHAR(255) NOT NULL,
    status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
    rejection_reason VARCHAR(500) NULL,
    submitted_by INT UNSIGNED NOT NULL,
    reviewed_by INT UNSIGNED NULL,
    reviewed_at DATETIME NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_brequest_district FOREIGN KEY (district_id) REFERENCES districts(id),
    CONSTRAINT fk_brequest_ds FOREIGN KEY (ds_division_id) REFERENCES ds_divisions(id),
    CONSTRAINT fk_brequest_gn FOREIGN KEY (gn_division_id) REFERENCES gn_divisions(id),
    CONSTRAINT fk_brequest_submitter FOREIGN KEY (submitted_by) REFERENCES users(id),
    CONSTRAINT fk_brequest_reviewer FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
    INDEX idx_brequest_status (status),
    INDEX idx_brequest_nic (nic)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS beneficiaries (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    registration_request_id INT UNSIGNED NULL UNIQUE,
    district_id INT UNSIGNED NOT NULL,
    ds_division_id INT UNSIGNED NOT NULL,
    gn_division_id INT UNSIGNED NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    nic VARCHAR(20) NOT NULL UNIQUE,
    date_of_birth DATE NOT NULL,
    gender ENUM('male','female','other') NOT NULL,
    phone VARCHAR(25) NULL,
    address VARCHAR(255) NOT NULL,
    disability VARCHAR(255) NOT NULL,
    status ENUM('active','inactive','deceased') NOT NULL DEFAULT 'active',
    approved_by INT UNSIGNED NOT NULL,
    approved_at DATETIME NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_beneficiary_request FOREIGN KEY (registration_request_id) REFERENCES beneficiary_registration_requests(id),
    CONSTRAINT fk_beneficiary_district FOREIGN KEY (district_id) REFERENCES districts(id),
    CONSTRAINT fk_beneficiary_ds FOREIGN KEY (ds_division_id) REFERENCES ds_divisions(id),
    CONSTRAINT fk_beneficiary_gn FOREIGN KEY (gn_division_id) REFERENCES gn_divisions(id),
    CONSTRAINT fk_beneficiary_approver FOREIGN KEY (approved_by) REFERENCES users(id),
    INDEX idx_beneficiary_geography (district_id,ds_division_id,gn_division_id),
    INDEX idx_beneficiary_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
