<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(403);exit("CLI only.\n");}
require_once __DIR__.'/../config/database.php';
$db=database();$db->beginTransaction();
try{
 $tag='smoke_'.bin2hex(random_bytes(4));$hash=password_hash('temporary',PASSWORD_DEFAULT);
 $user=$db->prepare("INSERT INTO users(full_name,username,password_hash,role,status) VALUES(:name,:username,:hash,:role,'active')");
 $ids=[];foreach(['admin','subject-officer','store-keeper','social-service-officer'] as $role){$user->execute(['name'=>'Smoke '.$role,'username'=>$tag.'_'.$role,'hash'=>$hash,'role'=>$role]);$ids[$role]=(int)$db->lastInsertId();}
 $db->prepare('INSERT INTO districts(name,created_by) VALUES(:name,:user)')->execute(['name'=>$tag,'user'=>$ids['admin']]);$district=(int)$db->lastInsertId();
 $db->prepare('INSERT INTO ds_divisions(district_id,name,created_by) VALUES(:district,:name,:user)')->execute(['district'=>$district,'name'=>$tag,'user'=>$ids['admin']]);$ds=(int)$db->lastInsertId();
 $db->prepare('INSERT INTO gn_divisions(ds_division_id,name,created_by) VALUES(:ds,:name,:user)')->execute(['ds'=>$ds,'name'=>$tag,'user'=>$ids['admin']]);$gn=(int)$db->lastInsertId();
 $db->prepare('UPDATE users SET district_id=:district,ds_division_id=:ds WHERE id=:officer')->execute(['district'=>$district,'ds'=>$ds,'officer'=>$ids['social-service-officer']]);
 $db->prepare("INSERT INTO item_categories(name,distribution_type,returnable,created_by) VALUES(:name,'direct',1,:user)")->execute(['name'=>$tag,'user'=>$ids['subject-officer']]);$category=(int)$db->lastInsertId();
 $db->prepare('INSERT INTO eligibility_rules(category_id,restriction_months,allow_multiple,updated_by) VALUES(:category,0,0,:user)')->execute(['category'=>$category,'user'=>$ids['subject-officer']]);
 $db->prepare("INSERT INTO inventory_items(item_name,category,category_id,variety,quantity) VALUES(:name,:category_name,:category,'Smoke',10)")->execute(['name'=>$tag,'category_name'=>$tag,'category'=>$category]);$item=(int)$db->lastInsertId();
 $db->prepare("INSERT INTO beneficiary_registration_requests(district_id,ds_division_id,gn_division_id,full_name,nic,date_of_birth,gender,address,disability,status,submitted_by,reviewed_by,reviewed_at) VALUES(:district,:ds,:gn,'Smoke Beneficiary',:nic,'1990-01-01','other','Smoke','Smoke','approved',:subject,:admin,NOW())")->execute(['district'=>$district,'ds'=>$ds,'gn'=>$gn,'nic'=>strtoupper(substr(hash('sha256',$tag),0,12)),'subject'=>$ids['subject-officer'],'admin'=>$ids['admin']]);$registration=(int)$db->lastInsertId();
 $db->prepare("INSERT INTO beneficiaries(registration_request_id,district_id,ds_division_id,gn_division_id,full_name,nic,date_of_birth,gender,address,disability,approved_by,approved_at) SELECT id,district_id,ds_division_id,gn_division_id,full_name,nic,date_of_birth,gender,address,disability,:admin,NOW() FROM beneficiary_registration_requests WHERE id=:id")->execute(['admin'=>$ids['admin'],'id'=>$registration]);$beneficiary=(int)$db->lastInsertId();
 $db->prepare("INSERT INTO goods_requests(item_id,quantity,destination_ds_division_id,justification,status,requested_by,approved_by,approved_at) VALUES(:item,5,:ds,'Smoke workflow','approved-awaiting-dispatch',:subject,:admin,NOW())")->execute(['item'=>$item,'ds'=>$ds,'subject'=>$ids['subject-officer'],'admin'=>$ids['admin']]);$goods=(int)$db->lastInsertId();
 $db->prepare('UPDATE inventory_items SET quantity=quantity-5 WHERE id=:item')->execute(['item'=>$item]);$db->prepare('INSERT INTO division_inventory(ds_division_id,item_id,quantity) VALUES(:ds,:item,5)')->execute(['ds'=>$ds,'item'=>$item]);$db->prepare("UPDATE goods_requests SET status='dispatched',dispatched_by=:store,dispatched_at=NOW() WHERE id=:id")->execute(['store'=>$ids['store-keeper'],'id'=>$goods]);
 $db->prepare('UPDATE division_inventory SET quantity=quantity-3 WHERE ds_division_id=:ds AND item_id=:item')->execute(['ds'=>$ds,'item'=>$item]);$db->prepare('INSERT INTO officer_pools(officer_id,item_id,allocated) VALUES(:officer,:item,3)')->execute(['officer'=>$ids['social-service-officer'],'item'=>$item]);
 $db->prepare("INSERT INTO distributions(beneficiary_id,item_id,quantity,distribution_type,source,distributed_by) VALUES(:beneficiary,:item,1,'direct','officer-pool',:officer)")->execute(['beneficiary'=>$beneficiary,'item'=>$item,'officer'=>$ids['social-service-officer']]);$distribution=(int)$db->lastInsertId();$db->prepare('UPDATE officer_pools SET distributed=distributed+1 WHERE officer_id=:officer AND item_id=:item')->execute(['officer'=>$ids['social-service-officer'],'item'=>$item]);
 $db->prepare("INSERT INTO item_returns(distribution_id,quantity,item_condition,reusable,restore_to,processed_by) VALUES(:distribution,1,'good',1,'officer-pool',:officer)")->execute(['distribution'=>$distribution,'officer'=>$ids['social-service-officer']]);$db->prepare('UPDATE officer_pools SET reused=reused+1 WHERE officer_id=:officer AND item_id=:item')->execute(['officer'=>$ids['social-service-officer'],'item'=>$item]);
 $central=(int)$db->query("SELECT quantity FROM inventory_items WHERE id=$item")->fetchColumn();$division=(int)$db->query("SELECT quantity FROM division_inventory WHERE ds_division_id=$ds AND item_id=$item")->fetchColumn();$pool=$db->query("SELECT allocated,distributed,reused,allocated-distributed+reused remaining FROM officer_pools WHERE officer_id={$ids['social-service-officer']} AND item_id=$item")->fetch();
 if($central!==5||$division!==2||(int)$pool['allocated']!==3||(int)$pool['distributed']!==1||(int)$pool['reused']!==1||(int)$pool['remaining']!==3)throw new RuntimeException('Stock balance assertion failed.');
 echo "[OK] central stock -> division stock -> officer pool -> distribution -> return\n";echo "[OK] final balances central=5 division=2 pool=3\n";
 $db->rollBack();echo "Smoke data rolled back; no dummy records retained.\n";
}catch(Throwable $e){if($db->inTransaction())$db->rollBack();fwrite(STDERR,"[FAIL] ".$e->getMessage()."\n");exit(1);}
