<?php
declare(strict_types=1);requireRole('admin');require_once __DIR__.'/../../config/database.php';$activePage='reports';$type=(string)($_GET['report']??'');$export=(string)($_GET['export']??'');
$reports=[
'inventory'=>['Inventory Report','Current stock levels by item, category and variety',['Item','Category','Variety','In Stock'],"SELECT i.item_name Item,COALESCE(c.name,i.category) Category,i.variety Variety,i.quantity `In Stock` FROM inventory_items i LEFT JOIN item_categories c ON c.id=i.category_id ORDER BY i.item_name,i.variety"],
'distribution'=>['Distribution Report','All distributions by date, region and distributor',['Reference','Beneficiary','Item','Qty','Type','Source','Officer','Date'],"SELECT CONCAT('DIST-',LPAD(d.id,4,'0')) Reference,b.full_name Beneficiary,CONCAT(i.item_name,IF(i.variety='', '',CONCAT(' / ',i.variety))) Item,d.quantity Qty,d.distribution_type Type,d.source Source,u.full_name Officer,d.distributed_at Date FROM distributions d JOIN beneficiaries b ON b.id=d.beneficiary_id JOIN inventory_items i ON i.id=d.item_id JOIN users u ON u.id=d.distributed_by ORDER BY d.id DESC"],
'beneficiary'=>['Beneficiary Report','Beneficiary geography and latest distribution',['Beneficiary','NIC','District','DS Division','Status','Last Distribution'],"SELECT b.full_name Beneficiary,b.nic NIC,d.name District,ds.name `DS Division`,b.status Status,MAX(x.distributed_at) `Last Distribution` FROM beneficiaries b JOIN districts d ON d.id=b.district_id JOIN ds_divisions ds ON ds.id=b.ds_division_id LEFT JOIN distributions x ON x.beneficiary_id=b.id GROUP BY b.id ORDER BY b.full_name"],
'pools'=>['Social Service Officer Pool Report','Quota versus distributed and remaining',['Officer','DS Division','Item','Allocated','Distributed','Reused','Remaining'],"SELECT u.full_name Officer,ds.name `DS Division`,CONCAT(i.item_name,IF(i.variety='', '',CONCAT(' / ',i.variety))) Item,p.allocated Allocated,p.distributed Distributed,p.reused Reused,(p.allocated-p.distributed+p.reused) Remaining FROM officer_pools p JOIN users u ON u.id=p.officer_id LEFT JOIN ds_divisions ds ON ds.id=u.ds_division_id JOIN inventory_items i ON i.id=p.item_id ORDER BY u.full_name,i.item_name"],
'procurement'=>['Procurement Cost Report','Supplier invoices, payments and balances',['Batch','Supplier','Bill','Total','Paid','Balance','Received'],"SELECT CONCAT('BAT-',LPAD(r.id,4,'0')) Batch,s.company_name Supplier,r.bill_number Bill,r.total_cost Total,r.paid_amount Paid,r.balance_amount Balance,r.received_date Received FROM stock_receipts r JOIN suppliers s ON s.id=r.supplier_id ORDER BY r.id DESC"],
'requests'=>['Request Status Report','Aid request pipeline and turnaround',['Request','Beneficiary','Item','Submitted By','Status','Submitted','Reviewed'],"SELECT CONCAT('AR-',LPAD(ar.id,4,'0')) Request,b.full_name Beneficiary,i.item_name Item,u.full_name `Submitted By`,ar.status Status,ar.created_at Submitted,ar.reviewed_at Reviewed FROM aid_requests ar JOIN beneficiaries b ON b.id=ar.beneficiary_id JOIN inventory_items i ON i.id=ar.item_id JOIN users u ON u.id=ar.submitted_by ORDER BY ar.id DESC"],
'returns'=>['Return & Reuse Report','Returns with condition and destination',['Return','Distribution','Beneficiary','Item','Qty','Condition','Reusable','Destination','Date'],"SELECT CONCAT('RET-',LPAD(r.id,4,'0')) `Return`,CONCAT('DIST-',LPAD(r.distribution_id,4,'0')) Distribution,b.full_name Beneficiary,i.item_name Item,r.quantity Qty,r.item_condition `Condition`,IF(r.reusable,'Yes','No') Reusable,r.restore_to Destination,r.processed_at Date FROM item_returns r JOIN distributions x ON x.id=r.distribution_id JOIN beneficiaries b ON b.id=x.beneficiary_id JOIN inventory_items i ON i.id=x.item_id ORDER BY r.id DESC"],
'audit'=>['Audit Log Report','Full recorded system activity',['Timestamp','User','Role','Module','Action','Reference','Status'],"SELECT a.created_at Timestamp,COALESCE(u.full_name,'System') User,a.role Role,a.module Module,a.action Action,a.record_reference Reference,a.status Status FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.id DESC"]];
$rows=[];$error='';if(isset($reports[$type])){try{$rows=database()->query($reports[$type][3])->fetchAll(PDO::FETCH_ASSOC);}catch(PDOException $e){error_log($e->getMessage());$error='Unable to generate this report.';}}
if($export==='csv'&&isset($reports[$type])){header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="widms-'.$type.'-'.date('Y-m-d').'.csv"');$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");fputcsv($out,$reports[$type][2]);foreach($rows as $row)fputcsv($out,array_values($row));fclose($out);exit;}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Reports | WIDMS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="assets/css/admin-dashboard.css" rel="stylesheet"><style>@media print{.sidebar,.topbar,.reports-grid,.report-actions{display:none!important}.admin-shell{margin:0}.dashboard-content{padding:0;overflow:visible}.report-preview{box-shadow:none}}</style></head><body><?php require __DIR__.'/../../includes/admin-sidebar.php';?><div class="admin-shell"><header class="topbar"><div class="d-flex align-items-center gap-3"><button class="menu-button" id="menu-button">&#9776;</button><h1>Reports</h1></div></header><main class="dashboard-content reports-page"><section class="reports-grid"><?php foreach($reports as $key=>$report):?><article class="report-card"><span class="report-icon">&#128202;</span><h2><?=htmlspecialchars($report[0],ENT_QUOTES,'UTF-8')?></h2><p><?=htmlspecialchars($report[1],ENT_QUOTES,'UTF-8')?></p><div><a class="admin-primary-action" href="dashboard.php?page=reports&amp;report=<?=$key?>">Generate</a><a class="outline-action" href="dashboard.php?page=reports&amp;report=<?=$key?>&amp;print=1">PDF</a><a class="outline-action" href="dashboard.php?page=reports&amp;report=<?=$key?>&amp;export=csv">CSV</a></div></article><?php endforeach;?></section><?php if(isset($reports[$type])):?><section class="admin-data-card report-preview" style="margin-top:14px"><div class="admin-data-header"><h2><?=htmlspecialchars($reports[$type][0],ENT_QUOTES,'UTF-8')?></h2><div class="report-actions"><button class="outline-action" onclick="window.print()">Print / Save PDF</button></div></div><?php if($error):?><div class="alert alert-danger"><?=$error?></div><?php endif;?><div class="admin-data-table-wrap"><table class="admin-data-table"><thead><tr><?php foreach($reports[$type][2] as $column):?><th><?=htmlspecialchars($column,ENT_QUOTES,'UTF-8')?></th><?php endforeach;?></tr></thead><tbody><?php if(!$rows):?><tr><td colspan="<?=count($reports[$type][2])?>" class="admin-empty-row">No records available for this report.</td></tr><?php else:foreach($rows as $row):?><tr><?php foreach($row as $value):?><td><?=htmlspecialchars((string)($value??'—'),ENT_QUOTES,'UTF-8')?></td><?php endforeach;?></tr><?php endforeach;endif;?></tbody></table></div></section><?php endif;?></main></div><script src="assets/js/admin-dashboard.js"></script><?php if(isset($_GET['print'])&&isset($reports[$type])):?><script>window.addEventListener('load',()=>window.print());</script><?php endif;?></body></html>
