<?php
declare(strict_types=1); requireRole('subject-officer'); require_once __DIR__.'/../../config/database.php'; require_once __DIR__.'/../../includes/activity.php';
$activePage='beneficiaries';$errors=[];$success=(string)($_SESSION['flash_success']??'');unset($_SESSION['flash_success']);$districts=$dsDivisions=$gnDivisions=$requests=$beneficiaries=[];
$values=['district_id'=>'','ds_division_id'=>'','gn_division_id'=>'','full_name'=>'','nic'=>'','date_of_birth'=>'','gender'=>'','phone'=>'','address'=>'','disability'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){
 foreach(array_keys($values) as $key)$values[$key]=trim((string)($_POST[$key]??''));
 $districtId=filter_var($values['district_id'],FILTER_VALIDATE_INT);$dsId=filter_var($values['ds_division_id'],FILTER_VALIDATE_INT);$gnId=filter_var($values['gn_division_id'],FILTER_VALIDATE_INT);
 if(!verifyCsrfToken((string)($_POST['csrf_token']??'')))$errors[]='Your session expired. Refresh and try again.';
 if(!$districtId||!$dsId||!$gnId)$errors[]='Select District, DS Division, and GN Division.';
 if(mb_strlen($values['full_name'])<2||mb_strlen($values['full_name'])>150)$errors[]='Enter a valid full name.';
 $nic=strtoupper(preg_replace('/\s+/','',$values['nic']));if(!preg_match('/^(?:[0-9]{9}[VX]|[0-9]{12})$/',$nic))$errors[]='Enter a valid Sri Lankan NIC.';
 $dob=DateTimeImmutable::createFromFormat('Y-m-d',$values['date_of_birth']);if(!$dob||$dob->format('Y-m-d')!==$values['date_of_birth']||$dob>new DateTimeImmutable('today'))$errors[]='Enter a valid date of birth.';
 if(!in_array($values['gender'],['male','female','other'],true))$errors[]='Select a gender.';
 if($values['phone']!==''&&!preg_match('/^[0-9+()\-\s]{7,25}$/',$values['phone']))$errors[]='Enter a valid phone number.';
 if(mb_strlen($values['address'])<5||mb_strlen($values['address'])>255)$errors[]='Enter a valid address.';
 if(mb_strlen($values['disability'])<2||mb_strlen($values['disability'])>255)$errors[]='Enter the nature of disability.';
 if(!$errors){try{$geo=database()->prepare('SELECT gn.id FROM gn_divisions gn JOIN ds_divisions ds ON ds.id=gn.ds_division_id WHERE gn.id=:gn AND ds.id=:ds AND ds.district_id=:district AND gn.status="active" AND ds.status="active"');$geo->execute(['gn'=>$gnId,'ds'=>$dsId,'district'=>$districtId]);if(!$geo->fetch())throw new RuntimeException('The selected geographic hierarchy is invalid.');$dup=database()->prepare("SELECT nic FROM beneficiaries WHERE nic=:nic1 UNION SELECT nic FROM beneficiary_registration_requests WHERE nic=:nic2 AND status='pending'");$dup->execute(['nic1'=>$nic,'nic2'=>$nic]);if($dup->fetch())throw new RuntimeException('This NIC is already registered or awaiting approval.');$s=database()->prepare('INSERT INTO beneficiary_registration_requests(district_id,ds_division_id,gn_division_id,full_name,nic,date_of_birth,gender,phone,address,disability,submitted_by) VALUES(:district,:ds,:gn,:name,:nic,:dob,:gender,:phone,:address,:disability,:user)');$s->execute(['district'=>$districtId,'ds'=>$dsId,'gn'=>$gnId,'name'=>$values['full_name'],'nic'=>$nic,'dob'=>$values['date_of_birth'],'gender'=>$values['gender'],'phone'=>$values['phone']?:null,'address'=>$values['address'],'disability'=>$values['disability'],'user'=>$_SESSION['user_id']]);$id=(int)database()->lastInsertId();logActivity('Beneficiaries','Submitted beneficiary registration — '.$values['full_name'],'BR-'.str_pad((string)$id,4,'0',STR_PAD_LEFT),'pending');$_SESSION['flash_success']='Beneficiary registration submitted for Admin approval.';unset($_SESSION['csrf_token']);header('Location: dashboard.php?page=beneficiaries');exit;}catch(Throwable $e){error_log($e->getMessage());$errors[]=$e instanceof RuntimeException?$e->getMessage():($e instanceof PDOException&&$e->getCode()==='23000'?'This NIC already exists.':'Unable to submit beneficiary registration.');}}
}
try{$districts=database()->query("SELECT id,name FROM districts WHERE status='active' ORDER BY name")->fetchAll();$dsDivisions=database()->query("SELECT id,district_id,name FROM ds_divisions WHERE status='active' ORDER BY name")->fetchAll();$gnDivisions=database()->query("SELECT id,ds_division_id,name FROM gn_divisions WHERE status='active' ORDER BY name")->fetchAll();$requests=database()->prepare('SELECT r.*,d.name district,ds.name ds_name FROM beneficiary_registration_requests r JOIN districts d ON d.id=r.district_id JOIN ds_divisions ds ON ds.id=r.ds_division_id WHERE r.submitted_by=:user ORDER BY r.id DESC');$requests->execute(['user'=>$_SESSION['user_id']]);$requests=$requests->fetchAll();$beneficiaries=database()->query('SELECT b.*,d.name district,ds.name ds_name FROM beneficiaries b JOIN districts d ON d.id=b.district_id JOIN ds_divisions ds ON ds.id=b.ds_division_id ORDER BY b.full_name')->fetchAll();}catch(PDOException $e){error_log($e->getMessage());$errors[]='Beneficiary workflow is unavailable. Import database/migration_beneficiaries.sql.';}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Beneficiary Management | WIDMS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="assets/css/admin-dashboard.css" rel="stylesheet"></head><body><?php require __DIR__.'/../../includes/subject-officer-sidebar.php';?><div class="admin-shell"><header class="topbar"><div class="d-flex align-items-center gap-3"><button class="menu-button" id="menu-button">&#9776;</button><h1>Beneficiary Management</h1></div></header><main class="dashboard-content beneficiary-workflow-page"><?php if($success):?><div class="alert alert-success"><?=htmlspecialchars($success,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($errors):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $error):?><li><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></li><?php endforeach;?></ul></div><?php endif;?>
<section class="admin-data-card"><div class="admin-data-header"><h2>Register New Beneficiary</h2></div><form method="post" class="beneficiary-registration-form"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken(),ENT_QUOTES,'UTF-8')?>"><div class="beneficiary-form-grid three"><label>District *<select id="district_id" name="district_id" required><option value="">Select District</option><?php foreach($districts as $r):?><option value="<?=(int)$r['id']?>"><?=htmlspecialchars($r['name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label>DS Division *<select id="ds_division_id" name="ds_division_id" required><option value="">Select DS Division</option><?php foreach($dsDivisions as $r):?><option value="<?=(int)$r['id']?>" data-parent="<?=(int)$r['district_id']?>"><?=htmlspecialchars($r['name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label>GN Division *<select id="gn_division_id" name="gn_division_id" required><option value="">Select GN Division</option><?php foreach($gnDivisions as $r):?><option value="<?=(int)$r['id']?>" data-parent="<?=(int)$r['ds_division_id']?>"><?=htmlspecialchars($r['name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label></div><div class="beneficiary-form-grid three"><label>Full Name *<input name="full_name" maxlength="150" required></label><label>NIC Number *<input name="nic" maxlength="20" required></label><label>Date of Birth *<input type="date" id="date_of_birth" name="date_of_birth" required><small id="beneficiary-age">Age: —</small></label><label>Gender *<select name="gender" required><option value="">Select</option><option value="male">Male</option><option value="female">Female</option><option value="other">Other</option></select></label><label>Phone<input name="phone" maxlength="25"></label><label>Nature of Disability *<input name="disability" maxlength="255" required></label></div><label class="beneficiary-full">Address *<textarea name="address" rows="2" maxlength="255" required></textarea></label><button class="admin-primary-action">Submit for Admin Approval</button></form></section>
<section class="admin-data-card beneficiary-list-card"><div class="admin-data-header"><h2>My Registration Requests</h2></div><div class="admin-data-table-wrap"><table class="admin-data-table"><thead><tr><th>ID</th><th>Name</th><th>NIC</th><th>District</th><th>DS Division</th><th>Submitted</th><th>Status</th><th>Admin Reason</th></tr></thead><tbody><?php if(!$requests):?><tr><td colspan="8" class="admin-empty-row">No registration requests submitted.</td></tr><?php else:foreach($requests as $r):?><tr><td>BR-<?=str_pad((string)$r['id'],4,'0',STR_PAD_LEFT)?></td><td><?=htmlspecialchars($r['full_name'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['nic'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['district'],ENT_QUOTES,'UTF-8')?></td><td><?=htmlspecialchars($r['ds_name'],ENT_QUOTES,'UTF-8')?></td><td><?=date('d M Y',strtotime($r['created_at']))?></td><td><?=ucfirst($r['status'])?></td><td><?=htmlspecialchars($r['rejection_reason']?:'—',ENT_QUOTES,'UTF-8')?></td></tr><?php endforeach;endif;?></tbody></table></div></section>
</main></div><script src="assets/js/admin-dashboard.js"></script><script src="assets/js/beneficiary-form.js"></script></body></html>
