<?php
declare(strict_types=1);
requireRole('subject-officer'); require_once __DIR__.'/../../config/database.php'; require_once __DIR__.'/../../includes/activity.php'; require_once __DIR__.'/../../includes/contact-lens-overview.php';
$activePage='contact-lens-orders'; $db=database(); $user=(int)$_SESSION['user_id']; $errors=[]; $success=(string)($_SESSION['flash_success']??''); unset($_SESSION['flash_success']);
function signedPower(float|string $p):string{return sprintf('%+.2f',(float)$p);} function lensRedirect(string $m):never{$_SESSION['flash_success']=$m;unset($_SESSION['csrf_token']);header('Location: dashboard.php?page=contact-lens-orders');exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!verifyCsrfToken((string)($_POST['csrf_token']??'')))$errors[]='Your session expired.'; $action=(string)($_POST['action']??'');
 if(!$errors)try{
  if($action==='create'){
   $supplier=filter_input(INPUT_POST,'supplier_id',FILTER_VALIDATE_INT);$ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['request_ids']??[])))));if(!$supplier||!$ids)throw new RuntimeException('Select a vendor and at least one approved contact lens request.');$db->beginTransaction();
   $q=$db->prepare("SELECT COUNT(*) FROM suppliers WHERE id=:id AND status='active'");$q->execute(['id'=>$supplier]);if(!$q->fetchColumn())throw new RuntimeException('Vendor is unavailable.');$marks=implode(',',array_fill(0,count($ids),'?'));
   $q=$db->prepare("SELECT ar.id,ar.quantity,ar.prescribed_power FROM aid_requests ar JOIN inventory_items i ON i.id=ar.item_id JOIN item_categories c ON c.id=i.category_id LEFT JOIN contact_lens_bulk_order_items bi ON bi.aid_request_id=ar.id WHERE ar.id IN ($marks) AND ar.status='approved' AND ar.prescribed_power IS NOT NULL AND LOWER(CONCAT(i.item_name,' ',i.variety,' ',c.name)) LIKE '%contact%lens%' AND bi.id IS NULL FOR UPDATE");$q->execute($ids);$selected=$q->fetchAll();if(count($selected)!==count($ids))throw new RuntimeException('A request is ineligible or already grouped.');
   $db->prepare("INSERT INTO contact_lens_bulk_orders(order_code,supplier_id,created_by) VALUES('PENDING',:supplier,:user)")->execute(['supplier'=>$supplier,'user'=>$user]);$oid=(int)$db->lastInsertId();$code='BO-CL-'.date('Y').'-'.str_pad((string)$oid,3,'0',STR_PAD_LEFT);$db->prepare('UPDATE contact_lens_bulk_orders SET order_code=:code WHERE id=:id')->execute(['code'=>$code,'id'=>$oid]);$in=$db->prepare('INSERT INTO contact_lens_bulk_order_items(bulk_order_id,aid_request_id,power,quantity) VALUES(:order,:aid,:power,:qty)');foreach($selected as $r)$in->execute(['order'=>$oid,'aid'=>$r['id'],'power'=>number_format((float)$r['prescribed_power'],2,'.',''),'qty'=>$r['quantity']]);$db->commit();logActivity('Contact Lens Bulk Orders','Created bulk order',$code,'draft');lensRedirect("Bulk order $code created.");
  }
  if($action==='submit'){$id=filter_input(INPUT_POST,'order_id',FILTER_VALIDATE_INT);$q=$db->prepare("UPDATE contact_lens_bulk_orders SET status='pending-admin-approval',submitted_at=NOW() WHERE id=:id AND created_by=:user AND status='draft'");$q->execute(['id'=>$id,'user'=>$user]);if(!$q->rowCount())throw new RuntimeException('Only your draft can be submitted.');lensRedirect('Bulk order submitted for Admin Gate 2 approval.');}
  if($action==='assign'){
   $aid=filter_input(INPUT_POST,'aid_request_id',FILTER_VALIDATE_INT);$db->beginTransaction();$q=$db->prepare("SELECT bi.power,bo.id bulk_id FROM contact_lens_bulk_order_items bi JOIN contact_lens_bulk_orders bo ON bo.id=bi.bulk_order_id WHERE bi.aid_request_id=:aid AND bo.created_by=:user AND bo.status IN ('partially-received','fully-received') FOR UPDATE");$q->execute(['aid'=>$aid,'user'=>$user]);$item=$q->fetch();if(!$item)throw new RuntimeException('Requirement is not ready for matching.');$q=$db->prepare("SELECT id,unit_code FROM contact_lens_units WHERE bulk_order_id=:bulk AND power=:power AND status='available' ORDER BY id LIMIT 1 FOR UPDATE");$q->execute(['bulk'=>$item['bulk_id'],'power'=>$item['power']]);$unit=$q->fetch();if(!$unit)throw new RuntimeException('No available lens has exact power '.signedPower($item['power']).'.');$db->prepare("UPDATE contact_lens_units SET status='reserved',aid_request_id=:aid,assigned_by=:user,assigned_at=NOW() WHERE id=:id")->execute(['aid'=>$aid,'user'=>$user,'id'=>$unit['id']]);$db->prepare("INSERT INTO contact_lens_unit_history(lens_unit_id,event_type,aid_request_id,power,notes,performed_by) VALUES(:unit,'assigned',:aid,:power,'Exact-power match',:user)")->execute(['unit'=>$unit['id'],'aid'=>$aid,'power'=>$item['power'],'user'=>$user]);$db->commit();lensRedirect('Exact-power lens '.$unit['unit_code'].' reserved.');
  }
  if($action==='handover'){
   $unit=filter_input(INPUT_POST,'unit_id',FILTER_VALIDATE_INT);$sso=filter_input(INPUT_POST,'sso_id',FILTER_VALIDATE_INT);$db->beginTransaction();$q=$db->prepare("SELECT lu.*,ar.beneficiary_id FROM contact_lens_units lu JOIN contact_lens_bulk_orders bo ON bo.id=lu.bulk_order_id JOIN aid_requests ar ON ar.id=lu.aid_request_id WHERE lu.id=:id AND bo.created_by=:user AND lu.status='reserved' FOR UPDATE");$q->execute(['id'=>$unit,'user'=>$user]);$lens=$q->fetch();if(!$lens)throw new RuntimeException('Reserved lens was not found.');$q=$db->prepare("SELECT COUNT(*) FROM users u JOIN beneficiaries b ON b.ds_division_id=u.ds_division_id WHERE u.id=:sso AND u.role='social-service-officer' AND u.status='active' AND b.id=:beneficiary");$q->execute(['sso'=>$sso,'beneficiary'=>$lens['beneficiary_id']]);if(!$q->fetchColumn())throw new RuntimeException('Select an active SSO from the beneficiary division.');$db->prepare("UPDATE contact_lens_units SET status='pending-handover',sso_id=:sso WHERE id=:id")->execute(['sso'=>$sso,'id'=>$unit]);$db->prepare("INSERT INTO contact_lens_unit_history(lens_unit_id,event_type,aid_request_id,power,notes,performed_by) VALUES(:unit,'handover',:aid,:power,'Sent to SSO',:user)")->execute(['unit'=>$unit,'aid'=>$lens['aid_request_id'],'power'=>$lens['power'],'user'=>$user]);$db->commit();lensRedirect('Lens sent to Pending Handover.');
  }
  if(in_array($action,['change-power','unavailable'],true)){
   $aid=filter_input(INPUT_POST,'aid_request_id',FILTER_VALIDATE_INT);$new=filter_input(INPUT_POST,'new_power',FILTER_VALIDATE_FLOAT);$db->beginTransaction();$q=$db->prepare("SELECT bi.id item_id,bi.power old_power,lu.id unit_id,lu.power unit_power FROM contact_lens_bulk_order_items bi JOIN contact_lens_bulk_orders bo ON bo.id=bi.bulk_order_id LEFT JOIN contact_lens_units lu ON lu.aid_request_id=bi.aid_request_id AND lu.status IN ('reserved','pending-handover') WHERE bi.aid_request_id=:aid AND bo.created_by=:user FOR UPDATE");$q->execute(['aid'=>$aid,'user'=>$user]);$row=$q->fetch();if(!$row)throw new RuntimeException('Requirement was not found.');if($action==='change-power'&&($new===false||$new < -30||$new > 30))throw new RuntimeException('Enter a valid new power.');if($row['unit_id']){$reason=$action==='change-power'?'Prescription changed from '.signedPower($row['old_power']).' to '.signedPower((float)$new):'Beneficiary unavailable for collection';$db->prepare("UPDATE contact_lens_units SET status='returned-to-vendor',returned_at=NOW(),return_reason=:reason WHERE id=:id")->execute(['reason'=>$reason,'id'=>$row['unit_id']]);$db->prepare("INSERT INTO contact_lens_unit_history(lens_unit_id,event_type,aid_request_id,power,notes,performed_by) VALUES(:unit,'returned-to-vendor',:aid,:power,:reason,:user)")->execute(['unit'=>$row['unit_id'],'aid'=>$aid,'power'=>$row['unit_power'],'reason'=>$reason,'user'=>$user]);}if($action==='change-power'){$p=number_format((float)$new,2,'.','');$db->prepare('UPDATE aid_requests SET prescribed_power=:p WHERE id=:aid')->execute(['p'=>$p,'aid'=>$aid]);$db->prepare('UPDATE contact_lens_bulk_order_items SET power=:p WHERE id=:id')->execute(['p'=>$p,'id'=>$row['item_id']]);}$db->commit();lensRedirect($action==='change-power'?'Prescription updated and any old reservation returned to the vendor.':'Lens returned to the vendor.');
  }
  throw new RuntimeException('Invalid workflow action.');
 }catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log($e->getMessage());$errors[]=$e instanceof RuntimeException?$e->getMessage():'Unable to update workflow.';}
}
try{$available=$db->query("SELECT ar.id,ar.quantity,ar.prescribed_power,b.full_name,b.nic FROM aid_requests ar JOIN beneficiaries b ON b.id=ar.beneficiary_id JOIN inventory_items i ON i.id=ar.item_id JOIN item_categories c ON c.id=i.category_id LEFT JOIN contact_lens_bulk_order_items bi ON bi.aid_request_id=ar.id WHERE ar.status='approved' AND ar.prescribed_power IS NOT NULL AND LOWER(CONCAT(i.item_name,' ',i.variety,' ',c.name)) LIKE '%contact%lens%' AND bi.id IS NULL ORDER BY ar.id")->fetchAll();$suppliers=$db->query("SELECT id,company_name FROM suppliers WHERE status='active' ORDER BY company_name")->fetchAll();$q=$db->prepare("SELECT bo.*,s.company_name,COUNT(bi.id) beneficiaries,COALESCE(SUM(bi.quantity),0) total_lenses,COALESCE(SUM(bi.received_quantity),0) received FROM contact_lens_bulk_orders bo JOIN suppliers s ON s.id=bo.supplier_id LEFT JOIN contact_lens_bulk_order_items bi ON bi.bulk_order_id=bo.id WHERE bo.created_by=:user GROUP BY bo.id ORDER BY bo.id DESC");$q->execute(['user'=>$user]);$orders=$q->fetchAll();$q=$db->prepare("SELECT bi.*,bo.order_code,bo.status order_status,b.full_name,b.nic,lu.id unit_id,lu.unit_code,lu.status unit_status FROM contact_lens_bulk_order_items bi JOIN contact_lens_bulk_orders bo ON bo.id=bi.bulk_order_id JOIN aid_requests ar ON ar.id=bi.aid_request_id JOIN beneficiaries b ON b.id=ar.beneficiary_id LEFT JOIN contact_lens_units lu ON lu.aid_request_id=ar.id WHERE bo.created_by=:user ORDER BY bi.id DESC");$q->execute(['user'=>$user]);$items=$q->fetchAll();$ssos=$db->query("SELECT id,full_name FROM users WHERE role='social-service-officer' AND status='active' ORDER BY full_name")->fetchAll();}catch(PDOException $e){error_log($e->getMessage());$available=$suppliers=$orders=$items=$ssos=[];$errors[]='Bulk workflow unavailable. Run migrations first.';}
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bulk Contact Lens Orders</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="assets/css/admin-dashboard.css" rel="stylesheet"></head><body><?php require __DIR__.'/../../includes/subject-officer-sidebar.php';?><div class="admin-shell"><header class="topbar"><h1>Bulk Contact Lens Procurement</h1></header><main class="dashboard-content admin-operation-page"><?php renderContactLensOverview($db);?><?php if($success):?><div class="alert alert-success"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($errors):?><div class="alert alert-danger"><?=htmlspecialchars(implode(' ',$errors))?></div><?php endif;?>
<section class="admin-data-card"><h2>Create Bulk Order from Gate 1 Approvals</h2><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken())?>"><input type="hidden" name="action" value="create"><label>Vendor <select name="supplier_id" required><option value="">Select vendor</option><?php foreach($suppliers as $s):?><option value="<?=(int)$s['id']?>"><?=htmlspecialchars($s['company_name'])?></option><?php endforeach;?></select></label><div class="admin-data-table-wrap"><table class="admin-data-table"><thead><tr><th></th><th>Aid Request</th><th>Beneficiary</th><th>NIC</th><th>Power</th><th>Qty</th></tr></thead><tbody><?php if(!$available):?><tr><td colspan="6">No approved ungrouped requirements.</td></tr><?php else:foreach($available as $r):?><tr><td><input type="checkbox" name="request_ids[]" value="<?=(int)$r['id']?>"></td><td>AR-<?=str_pad((string)$r['id'],4,'0',STR_PAD_LEFT)?></td><td><?=htmlspecialchars($r['full_name'])?></td><td><?=htmlspecialchars($r['nic'])?></td><td><?=signedPower($r['prescribed_power'])?></td><td><?=(int)$r['quantity']?></td></tr><?php endforeach;endif;?></tbody></table></div><button class="admin-primary-action">Create Draft Bulk Order</button></form></section>
<section class="admin-data-card"><h2>My Bulk Orders</h2><div class="admin-data-table-wrap"><table class="admin-data-table"><thead><tr><th>Order</th><th>Vendor</th><th>Beneficiaries</th><th>Ordered</th><th>Received</th><th>Pending</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><?=htmlspecialchars($o['order_code'])?></td><td><?=htmlspecialchars($o['company_name'])?></td><td><?=(int)$o['beneficiaries']?></td><td><?=(int)$o['total_lenses']?></td><td><?=(int)$o['received']?></td><td><?=max(0,(int)$o['total_lenses']-(int)$o['received'])?></td><td><?=ucwords(str_replace('-',' ',$o['status']))?></td><td><?php if($o['status']==='draft'):?><form method="post"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken())?>"><input type="hidden" name="action" value="submit"><input type="hidden" name="order_id" value="<?=(int)$o['id']?>"><button class="approve-button">Submit Gate 2</button></form><?php else:?><?=htmlspecialchars($o['rejection_reason']?:'—')?><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="admin-data-card"><h2>Matching and Exceptions</h2><div class="admin-data-table-wrap"><table class="admin-data-table"><thead><tr><th>Order</th><th>Beneficiary / NIC</th><th>Power</th><th>Unit</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($items as $r):?><tr><td><?=htmlspecialchars($r['order_code'])?></td><td><?=htmlspecialchars($r['full_name'].' / '.$r['nic'])?></td><td><?=signedPower($r['power'])?></td><td><?=htmlspecialchars($r['unit_code']?:'—')?></td><td><?=ucwords(str_replace('-',' ',$r['unit_status']?:$r['order_status']))?></td><td><?php if(!$r['unit_id']&&in_array($r['order_status'],['partially-received','fully-received'],true)):?><form method="post" class="d-inline"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken())?>"><input type="hidden" name="action" value="assign"><input type="hidden" name="aid_request_id" value="<?=(int)$r['aid_request_id']?>"><button class="approve-button">Exact Match</button></form><?php endif;?><?php if($r['unit_status']==='reserved'):?><form method="post" class="d-inline"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken())?>"><input type="hidden" name="action" value="handover"><input type="hidden" name="unit_id" value="<?=(int)$r['unit_id']?>"><select name="sso_id" required><option value="">SSO</option><?php foreach($ssos as $s):?><option value="<?=(int)$s['id']?>"><?=htmlspecialchars($s['full_name'])?></option><?php endforeach;?></select><button class="approve-button">Handover</button></form><?php endif;?><form method="post" class="d-inline"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken())?>"><input type="hidden" name="action" value="change-power"><input type="hidden" name="aid_request_id" value="<?=(int)$r['aid_request_id']?>"><input type="number" name="new_power" step="0.01" min="-30" max="30" placeholder="New power" required><button>Change</button></form><?php if(in_array($r['unit_status'],['reserved','pending-handover'],true)):?><form method="post" class="d-inline"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken())?>"><input type="hidden" name="action" value="unavailable"><input type="hidden" name="aid_request_id" value="<?=(int)$r['aid_request_id']?>"><button class="reject-button">Unavailable</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
</main></div><script src="assets/js/admin-dashboard.js"></script></body></html>
