<?php
declare(strict_types=1);
requireRole('subject-officer');
require_once __DIR__.'/../../config/database.php';
require_once __DIR__.'/../../includes/activity.php';
require_once __DIR__.'/../../includes/contact-lens-overview.php';
$activePage='contact-lens-orders';$db=database();$errors=[];$success=(string)($_SESSION['flash_success']??'');unset($_SESSION['flash_success']);
$values=['beneficiary_name'=>'','nic'=>'','prescribed_power'=>'','division_id'=>'','supplier_id'=>''];
if($_SERVER['REQUEST_METHOD']==='POST'){
 foreach(array_keys($values) as $key)$values[$key]=trim((string)($_POST[$key]??''));$division=filter_var($values['division_id'],FILTER_VALIDATE_INT);$supplier=filter_var($values['supplier_id'],FILTER_VALIDATE_INT);$power=filter_var($values['prescribed_power'],FILTER_VALIDATE_FLOAT);$nic=strtoupper(preg_replace('/\s+/','',$values['nic']));
 if(!verifyCsrfToken((string)($_POST['csrf_token']??'')))$errors[]='Your session expired. Refresh the page and try again.';if(mb_strlen($values['beneficiary_name'])<2||mb_strlen($values['beneficiary_name'])>150)$errors[]='Enter the beneficiary name.';if($nic!==''&&!preg_match('/^(?:[0-9]{9}[VX]|[0-9]{12})$/',$nic))$errors[]='Enter a valid Sri Lankan NIC or leave it blank.';if(!$division||!$supplier)$errors[]='Select a division and company.';if($power===false||$power < -30||$power > 30)$errors[]='Select a valid prescribed power.';
 if(!$errors)try{$db->beginTransaction();if($nic!==''){$q=$db->prepare("SELECT id FROM beneficiaries WHERE ds_division_id=:division AND status='active' AND nic=:nic ORDER BY id DESC LIMIT 1 FOR UPDATE");$q->execute(['division'=>$division,'nic'=>$nic]);}else{$q=$db->prepare("SELECT id FROM beneficiaries WHERE ds_division_id=:division AND status='active' AND full_name=:name ORDER BY id DESC LIMIT 1 FOR UPDATE");$q->execute(['division'=>$division,'name'=>$values['beneficiary_name']]);}$beneficiary=(int)$q->fetchColumn();if(!$beneficiary)throw new RuntimeException('No active registered beneficiary matches that name, NIC, and division. Register the beneficiary first.');$item=(int)$db->query("SELECT i.id FROM inventory_items i LEFT JOIN item_categories c ON c.id=i.category_id WHERE LOWER(CONCAT(COALESCE(i.item_name,''),' ',COALESCE(i.variety,''),' ',COALESCE(c.name,i.category,''))) LIKE '%contact%lens%' ORDER BY i.id LIMIT 1")->fetchColumn();if(!$item)throw new RuntimeException('The Contact Lens inventory item is not configured.');$q=$db->prepare("SELECT COUNT(*) FROM aid_requests WHERE beneficiary_id=:beneficiary AND item_id=:item AND status IN ('pending','approved','goods-requested')");$q->execute(['beneficiary'=>$beneficiary,'item'=>$item]);if($q->fetchColumn())throw new RuntimeException('This beneficiary already has an active contact lens request.');$q=$db->prepare("SELECT company_name FROM suppliers WHERE id=:id AND status='active'");$q->execute(['id'=>$supplier]);$company=$q->fetchColumn();if(!$company)throw new RuntimeException('The selected company is unavailable.');$db->prepare("INSERT INTO aid_requests(beneficiary_id,item_id,quantity,disability_notes,prescribed_power,notes,status,submitted_by) VALUES(:beneficiary,:item,1,'Visual Impairment',:power,:notes,'pending',:user)")->execute(['beneficiary'=>$beneficiary,'item'=>$item,'power'=>number_format((float)$power,2,'.',''),'notes'=>'Preferred company: '.$company,'user'=>$_SESSION['user_id']]);$id=(int)$db->lastInsertId();$db->commit();logActivity('Contact Lens Orders','Submitted contact lens request for Admin approval','CL-'.str_pad((string)$id,3,'0',STR_PAD_LEFT),'pending');$_SESSION['flash_success']='Contact lens request submitted to Admin for approval.';unset($_SESSION['csrf_token']);header('Location: dashboard.php?page=contact-lens-orders');exit;}catch(Throwable $e){if($db->inTransaction())$db->rollBack();error_log($e->getMessage());$errors[]=$e instanceof RuntimeException?$e->getMessage():'Unable to submit the contact lens request.';}
}
try{$divisions=$db->query("SELECT id,name FROM ds_divisions WHERE status='active' ORDER BY name")->fetchAll();$suppliers=$db->query("SELECT id,company_name FROM suppliers WHERE status='active' ORDER BY company_name")->fetchAll();}catch(PDOException $e){error_log($e->getMessage());$divisions=$suppliers=[];$errors[]='Request form options are unavailable.';}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Contact Lens Orders | WIDMS</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="assets/css/admin-dashboard.css" rel="stylesheet"></head><body><?php require __DIR__.'/../../includes/subject-officer-sidebar.php';?><div class="admin-shell"><header class="topbar"><div class="d-flex align-items-center gap-3"><button type="button" class="menu-button" id="menu-button" aria-label="Open navigation">&#9776;</button><h1>Contact Lens Orders</h1></div></header><main class="dashboard-content admin-operation-page contact-lens-overview-page">
<?php if($success):?><div class="alert alert-success"><?=htmlspecialchars($success,ENT_QUOTES,'UTF-8')?></div><?php endif;?><?php if($errors):?><div class="alert alert-danger"><ul class="mb-0"><?php foreach($errors as $error):?><li><?=htmlspecialchars($error,ENT_QUOTES,'UTF-8')?></li><?php endforeach;?></ul></div><?php endif;?>
<section class="admin-data-card lens-request-card"><div class="admin-data-header"><h2><span class="lens-blue-dot"></span>New Contact Lens Request</h2></div><form method="post" class="lens-request-form"><input type="hidden" name="csrf_token" value="<?=htmlspecialchars(csrfToken(),ENT_QUOTES,'UTF-8')?>"><div class="lens-request-grid top-row"><label>Beneficiary Name *<input name="beneficiary_name" value="<?=htmlspecialchars($values['beneficiary_name'],ENT_QUOTES,'UTF-8')?>" placeholder="Full name" maxlength="150" required></label><label>NIC Number<input name="nic" value="<?=htmlspecialchars($values['nic'],ENT_QUOTES,'UTF-8')?>" placeholder="If available" maxlength="20"></label></div><div class="lens-request-grid"><label>Prescribed Power *<select name="prescribed_power" required><option value="">Select Power</option><?php for($p=-30;$p<=30;$p+=.25):?><option value="<?=number_format($p,2,'.','')?>" <?=$values['prescribed_power']===number_format($p,2,'.','')?'selected':''?>><?=sprintf('%+.2f',$p)?></option><?php endfor;?></select></label><label>Division *<select name="division_id" required><option value="">Select division</option><?php foreach($divisions as $row):?><option value="<?=(int)$row['id']?>" <?=$values['division_id']===(string)$row['id']?'selected':''?>><?=htmlspecialchars($row['name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label><label>Company *<select name="supplier_id" required><option value="">Select company</option><?php foreach($suppliers as $row):?><option value="<?=(int)$row['id']?>" <?=$values['supplier_id']===(string)$row['id']?'selected':''?>><?=htmlspecialchars($row['company_name'],ENT_QUOTES,'UTF-8')?></option><?php endforeach;?></select></label></div><button class="admin-primary-action lens-submit-button">Submit Lens Request to Admin</button></form></section>
<?php renderContactLensOverview($db);?></main></div><script src="assets/js/admin-dashboard.js"></script></body></html>
